services:
  # 1. POSTGRESQL VERITABANI SERVISI
  postgresdb:
    image: postgres:14-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gymdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "gymdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - project_network
# 2. REDIS Ã–NBELLEK SERVISI
  redis:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - project_network

  # 3. ASP.NET CORE API SERVISI
  api:
    build:
      context: ./Project.API
      target: final
    container_name: api_server
    ports:
      - "8080:8080"
    restart: always
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgresdb;Database=gymdb;Username=postgres;Password=postgres"
      ConnectionStrings__Redis: "redis:6379"
      AppSettings__Token: "mysupersecretkey123456789012345678901234567890"
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENV:-Development}
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
    depends_on:
      postgresdb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - project_network

  # 4. ASP.NET CORE WEB UI SERVISI
  web:
    build:
      context: ./Project.web
      target: final
    container_name: web_server
    ports:
      - "0.0.0.0:5002:8080"
    restart: always
    environment:
      ApiSettings__ProjectApiBaseUrl: "http://api:8080"
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENV:-Development}
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
    depends_on:
      - api
    networks:
      - project_network

networks:
  project_network:
    driver: bridge

volumes:
  postgres_data:
